"""empty message

Revision ID: 6073d50866b8
Revises: b7ec78327a3e
Create Date: 2023-11-23 18:49:25.760467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6073d50866b8'
down_revision = 'b7ec78327a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=250), nullable=True))
        batch_op.drop_column('telefono ')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono ', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
